version: '3.8'

services:
  registration-app:
    build: .
    image: registration-app:latest
    container_name: registration-app-container
    ports:
      - "8081:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
